name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Maximize Nix Disk Space (Rampage Mode)
        uses: wimpysworld/nothing-but-nix@v9
        with:
          #DOC: https://github.com/marketplace/actions/nothing-but-nix
          hatchet-protocol: 'rampage' # Rampage: Most aggressive mode
          root-safe-haven: '2048'   # Reserve 2GB on /
          mnt-safe-haven: '2048'     # Reserve 2GB on /mnt

      - name: Install Nix
        uses: determinateSystems/nix-installer-action@v9

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: flake-fhs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Run flake check
        run: nix flake check

      - name: Run template validation
        run: nix develop --command python checks/template-validation/validators.py
